name: hcrl
dependencies:
  - base >= 4.14 && < 5
  - relude

  - websockets
  - wreq
  - wuss

  - file-embed
  - JuicyPixels

  - aeson
  - containers
  - delay
  - fixed-vector
  - lens
  - megaparsec
  - random
library:
  source-dirs: .
  exposed-modules:
    - Game
    - Slack
executable:
  main: Main.hs
  source-dirs: .
