name: rogue
ghc-options: -O2 -Wall
dependencies:
  - base >= 4.14 && < 5
  - relude

  - websockets
  - wreq
  - wuss

  # only useful for image mode
  - file-embed
  - JuicyPixels

  - aeson
  - aeson-pretty
  - astar
  - async
  - base64
  - containers
  - data-default
  - delay
  - fixed-vector
  - lens
  - megaparsec
  - MonadRandom
  # - random
  - split
executable:
  main: Main.hs
  source-dirs: src
